### ISSUE TITLE
项目很好用，催更

### ISSUE THREAD

**Issue by hnshandy** [qwwuyu/FileManage#1]
手机和电脑局域网互传文件正好是我需要的功能，可以不用微信和插数据线了。

网页端确实不太好看，催更用vue写。

另外，手机和电脑传字符串文本，而不仅仅传文件，也有这个需求。

**Comment by qwwuyu** [comment]
互传文本我也经常用,是该加一个了,周末花时间弄弄.
好久没写前端代码了,短期内难完成了,用vue是想把当前代码规范一下~

**Comment by hnshandy** [comment]
我也不会网页开发。。

网页样式[这个](https://github.com/CPPAlien/FileTransfer)项目做得比较好看 ，不过你的功能更全，列出了手机文件列表，而且能向手机发送安装APK的指令，如果两者能结合就好了。

文本互传的话，由于手机的服务端，电脑浏览器是客户端，根据HTTP特性，当浏览器向手机传文本，手机不需要任何刷新操作就能直接显示吧？而手机向电脑传文本，是不是电脑浏览器必须刷新一次才能获取文本？

**Comment by qwwuyu** [comment]
> 

暂时是这样想的,浏览器点击一次按键主动请求才能获取最新的数据.手机这边收到请求是可以直接复制到剪切板上.
我在想做个手机和网页界面,列表文本形式,可以选择储存在数据库或内存中,两端都可以浏览复制添加删除,用于备份一点临时文本数据.

**Comment by hnshandy** [comment]
依然建议优化下网页的显示效果，Material Design看起来不错，刚发现[一个库](https://github.com/zdhxiong/mdui)，不知能不能用得上。
我看了assets目录下的文件，有1.86MB，太多东西了，里面还有一堆jQuery，我没办法修改和优化，不知能否精简掉一些没用的文件？

**Comment by qwwuyu** [comment]
正好工作用到了react,练手重构了前端代码,太懒了,开发的比较慢...
新增了文本互传,上传功能优化下UI,支持拖拽了.
整体UI还是比较难优化,没啥设计思维.
